[package]
name = "pgen-cli"
version = "0.1.0"
authors = ["Sean Newman <sxn6296@rit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
structopt = "0.3.21"
